### ISSUE TITLE
Pool and connect() with Momoko 2.0.0

### ISSUE THREAD

**Issue by vejnar** [FSX/momoko#107]
I am trying to switch to Momoko 2.0.0 but I have a two problems.

- In the tutorial, these lines call the `connect()` method:
```
future = application.db.connect()
ioloop.add_future(future, lambda f: ioloop.stop())
ioloop.start()
```
I am using a `Pool`. When I init one and directly call `execute()` on it, I get:
```
assert self.conns.dead, "BUG: dont' call reanimate when there is no one to reanimate"
```
Which is fixable by adding the 3 lines above. It wasn't like that with the previous version. Is connecting first necessary now? Could you please clarify? BTW not requiring a first connect would be nice.

- In the tutorial, an ioloop instance created with `ioloop = IOLoop.instance()` is passed to init a `Pool`. Is that necessary?

Thanks a lot for your help and for developing and maintaining Momoko. It's great!

**Comment by haizaar** [comment]
Yes, you need to `connect`. Previously `Pool` was connecting implicitly in the constructor. I have changed it for several reasons:
 * You'd want to connect to db before starting to serve http requests. So you need to init `Pool` and wait it to connect to db before you start listening. Previously `Pool` used a `on_connect_callback` that you can use to get notified that all connection attempts are finished. Now we use futures, but you can not return a future from a constructor, so a separate method is required. This approach also hints a user that he'll better wait this future to resolve to make sure that database is ready. I guess previously some people were just initializing Pool "blindly" and since connections were created quite fast, never noticed that they have a race condition - which may work, but it's not how we want to build software, right?
 * I believe that from OOP perspective, creating db connections is not a part of `Pool` object initialization. And there is no real need to bind them together. So I did the separation.
 * You may want to inspect db connectivity state and do something different if, for example, database service is dead, instead of always firing up HTTP server.

Regarding your second question: `Pool` constructor will do
`self.ioloop = ioloop or IOLoop.instance()` if you don't pass your own `ioloop` instance. The tutorial does this explicitly to demonstrate the ability.

**Comment by vejnar** [comment]
OK. Thanks. Would be nice to clarify that in the tutorial.

**Comment by haizaar** [comment]
You are welcome to submit a pull request :)
